module.exports = {
  projects: [
    '<rootDir>/apps/workplace',
    '<rootDir>/apps/concierge',
    '<rootDir>/apps/control',
    '<rootDir>/apps/booking-panel',
    '<rootDir>/apps/map-kiosk',
    '<rootDir>/apps/visitor-kiosk',
    '<rootDir>/apps/caterer-ui',
    '<rootDir>/libs/bookings',
    '<rootDir>/libs/calendar',
    '<rootDir>/libs/catering',
    '<rootDir>/libs/common',
    '<rootDir>/libs/components',
    '<rootDir>/libs/events',
    '<rootDir>/libs/explore',
    '<rootDir>/libs/form-fields',
    '<rootDir>/libs/mocks',
    '<rootDir>/libs/organisation',
    '<rootDir>/libs/spaces',
    '<rootDir>/libs/users',
  ],
};
