module.exports = {
    projects: [
        '<rootDir>/apps/workplace',
        '<rootDir>/libs/components',
        '<rootDir>/libs/common',
        '<rootDir>/libs/bookings',
        '<rootDir>/libs/calendar',
        '<rootDir>/libs/catering',
        '<rootDir>/libs/events',
        '<rootDir>/libs/explore',
        '<rootDir>/libs/mocks',
        '<rootDir>/libs/organisation',
        '<rootDir>/libs/spaces',
        '<rootDir>/libs/users',
        '<rootDir>/apps/booking-panel',
        '<rootDir>/apps/concierge',
        '<rootDir>/apps/visitor-kiosk',
        '<rootDir>/apps/control',
        '<rootDir>/apps/caterer-ui',
        '<rootDir>/apps/map-kiosk',
    ],
};
