/** PARK-13: required restriction in the parking REQUEST flow.
 * Developer clarification 2026-09-22: ordinary space booking is not this feature.
 * Verify missing-choice validation and persistence of a selected restriction.
 */
import { randomUUID } from 'node:crypto';
import type { Request } from '@playwright/test';
import { getBooking, listBookings, STAFF_API } from '../../../../e2e/support/api';
import { expect, test } from '../../../../e2e/support/fixtures';
import { useSettings } from '../../../../e2e/support/parking/parking.settings';

test('a parking request requires and stores the selected restriction', async ({
    staffPage,
    staffApi,
}, testInfo) => {
    let booking_id: number | undefined;
    const restriction_id = `e2e-covered-${randomUUID()}`;
    const posts: Request[] = [];
    staffPage.on('request', (r) => {
        if (
            r.method() === 'POST' &&
            new URL(r.url()).pathname === `${STAFF_API}/bookings`
        )
            posts.push(r);
    });
    await useSettings(staffPage, {
        'app.parking.require_space_restriction': true,
        'app.parking.request_space_restrictions': [
            { id: restriction_id, name: 'E2E covered parking' },
        ],
    });
    try {
        await staffPage.goto('/#/book/parking-request/form');
        const form = staffPage.locator('parking-request-form');
        await expect(form).toBeVisible();
        const restrictions = form.locator(
            'mat-radio-group[aria-labelledby="parking-space-restrictions-label"]',
        );
        await expect(restrictions).toBeVisible();
        await expect(restrictions).toHaveAttribute('aria-required', 'true');
        await form.locator('button[confirm]').click();
        await expect(restrictions).toHaveAttribute('aria-invalid', 'true');
        expect(posts).toHaveLength(0);
        await restrictions
            .getByRole('radio', { name: 'E2E covered parking' })
            .check();
        await expect(restrictions).toHaveAttribute('aria-invalid', 'false');
        await staffPage.screenshot({
            path: testInfo.outputPath('parking-request-restriction.png'),
        });
        const [response] = await Promise.all([
            staffPage.waitForResponse(
                (r) =>
                    r.request().method() === 'POST' &&
                    new URL(r.url()).pathname === `${STAFF_API}/bookings`,
            ),
            form.locator('button[confirm]').click(),
        ]);
        const body = await response.json();
        booking_id = body.id;
        expect(response.status()).toBeLessThan(300);
        const stored = await getBooking(staffApi, booking_id!);
        await testInfo.attach('parking-request-evidence', {
            body: JSON.stringify({
                booking_id,
                status: response.status(),
                asset_id: stored.asset_id,
                booking_type: stored.booking_type,
                extension_data: stored.extension_data,
            }),
            contentType: 'application/json',
        });
        expect(stored.booking_type).toBe('parking');
        expect(stored.asset_id).toContain('unallocated');
        expect(stored.extension_data).toMatchObject({
            space_restrictions: restriction_id,
        });
    } finally {
        // Recover writes even when an assertion fails before the response is read.
        // Match only assets generated by this attempt; never sweep shared users.
        const ids = new Set<number>(booking_id == null ? [] : [booking_id]);
        const recovery = await Promise.allSettled(posts.map(async (request) => {
            const response = await request.response();
            const body = await response?.json().catch(() => undefined);
            if (typeof body?.id === 'number') ids.add(body.id);
            const submitted = request.postDataJSON();
            if (submitted?.asset_id && submitted.booking_start && submitted.booking_end) {
                const bookings = await listBookings(
                    staffApi, 'parking', submitted.booking_start, submitted.booking_end,
                );
                for (const booking of bookings) {
                    if (booking.asset_id === submitted.asset_id && !booking.deleted) {
                        ids.add(booking.id);
                    }
                }
            }
        }));
        const cleanup = await Promise.allSettled([...ids].map(async (id) => {
            const response = await staffApi.delete(`${STAFF_API}/bookings/${id}`);
            expect(response.ok() || response.status() === 404).toBeTruthy();
            await expect.poll(async () => {
                const remaining = await staffApi.get(`${STAFF_API}/bookings/${id}`);
                if (remaining.status() === 404) return true;
                expect(remaining.ok()).toBeTruthy();
                return (await remaining.json()).deleted === true;
            }).toBe(true);
        }));
        await testInfo.attach('parking-request-cleanup', {
            body: JSON.stringify({ booking_ids: [...ids], results: cleanup.map((r) => r.status) }),
            contentType: 'application/json',
        });
        for (const result of [...recovery, ...cleanup]) {
            if (result.status === 'rejected') throw result.reason;
        }
    }
});
