import {
    getLastCronRunTimestampInRange,
    getNextCronRunTimestampInRange,
} from '../app/cron-helpers';

function localDate(
    year: number,
    month: number,
    day: number,
    hour = 0,
    minute = 0,
) {
    return new Date(year, month - 1, day, hour, minute, 0, 0);
}

function expectLocalDate(value: number | null, expected: Date) {
    expect(value).toBeTruthy();
    if (!value) throw new Error('Expected cron result');
    expect(new Date(value * 1000)).toEqual(expected);
}

describe('cron helpers', () => {
    it('matches minute interval schedules generated by signage manager', () => {
        const result = getNextCronRunTimestampInRange(
            '*/15 * * * *',
            60 * 60,
            localDate(2026, 3, 2, 10, 7).getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 2, 10, 15));
    });

    it('matches hour interval schedules generated by signage manager', () => {
        const result = getNextCronRunTimestampInRange(
            '0 */4 * * *',
            24 * 60 * 60,
            localDate(2026, 3, 2, 9, 30).getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 2, 12, 0));
    });

    it('matches monthly day schedules generated by signage manager', () => {
        const result = getNextCronRunTimestampInRange(
            '0 9 1,15 * *',
            31 * 24 * 60 * 60,
            localDate(2026, 3, 2, 9, 0).getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 15, 9, 0));
    });

    it('matches monthly weekday schedules with signage manager AND semantics', () => {
        const result = getNextCronRunTimestampInRange(
            '0 9 1-7,15-21 * 1',
            31 * 24 * 60 * 60,
            localDate(2026, 3, 2, 9, 1).getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 16, 9, 0));
    });

    it('matches ranged step values in custom schedules', () => {
        const result = getNextCronRunTimestampInRange(
            '0 9-17/2 * * *',
            24 * 60 * 60,
            localDate(2026, 3, 2, 10, 0).getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 2, 11, 0));
    });

    it('allows extra whitespace around cron fields', () => {
        const result = getNextCronRunTimestampInRange(
            '  0   9   *   *   1-5  ',
            7 * 24 * 60 * 60,
            localDate(2026, 3, 8, 10, 0).getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 9, 9, 0));
    });

    it('rejects cron strings that are not five fields', () => {
        expect(() =>
            getNextCronRunTimestampInRange(
                '0 9 * *',
                24 * 60 * 60,
                localDate(2026, 3, 2, 10, 0).getTime(),
            ),
        ).toThrow('Invalid CRON string: Must have 5 parts.');
    });

    it('finds the last run of a daily schedule', () => {
        const result = getLastCronRunTimestampInRange(
            '0 6 * * *',
            12 * 60 * 60,
            localDate(2026, 3, 3, 7, 30).getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 3, 6, 0));
    });

    it('returns the most recent run when several fall inside the window', () => {
        const result = getLastCronRunTimestampInRange(
            '0 */6 * * *',
            12 * 60 * 60,
            localDate(2026, 3, 3, 7, 0).getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 3, 6, 0));
    });

    it('matches a run in the same minute as the search start', () => {
        const now = localDate(2026, 3, 3, 6, 0);
        now.setSeconds(20);
        const result = getLastCronRunTimestampInRange(
            '0 6 * * *',
            30,
            now.getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 3, 6, 0));
    });

    it('returns null when the last run predates the search window', () => {
        const result = getLastCronRunTimestampInRange(
            '0 6 * * *',
            60 * 60,
            localDate(2026, 3, 3, 8, 0).getTime(),
        );

        expect(result).toBeNull();
    });

    it('finds the last weekday run across a weekend', () => {
        const result = getLastCronRunTimestampInRange(
            '0 9 * * 1-5',
            3 * 24 * 60 * 60,
            localDate(2026, 3, 8, 10, 0).getTime(),
        );

        expectLocalDate(result, localDate(2026, 3, 6, 9, 0));
    });

    it('rejects last-run cron strings that are not five fields', () => {
        expect(() =>
            getLastCronRunTimestampInRange(
                '0 9 * *',
                24 * 60 * 60,
                localDate(2026, 3, 2, 10, 0).getTime(),
            ),
        ).toThrow('Invalid CRON string: Must have 5 parts.');
    });
});
