const custom_reports = [];

const app = {
    name: 'Concierge',
    title: 'PlaceOS',
    description: 'Concierge UI',
    short_name: 'PlaceOS',
    logo_light: 'assets/logo-light.svg',
    logo_dark: 'assets/logo-dark.svg',
    default_route: '/book/rooms',
    currency: 'USD',
    use_24_hour_time: false,
    admin_group: 'concierge_admins',
    features: [
        'spaces',
        'zones',
        'desks',
        'parking',
        'visitors',
        'assets',
        'facilities',
        'internal-users',
        'points',
        'surveys',
        'catering',
        'events',
        'booking-report',
        'attendance-report',
        'contact-tracing-report',
        'signage',
        'events',
        'email-templates',
    ],
    guests: { vaccine_check: true },
    delegated: false,
    has_uploads: true,
    custom_reports,
    desks: {
        use_assets: false,
        can_book_for_others: true,
        max_assigned_count: 0,
        hide_user_list_download: true,
    },
    bookings: { can_book_for_others: true, use_building_timezone: false },
    visitors: { all_visitors_action_window: 15 },
    reports: { attendance_include_weekends: false },
    parking: {
        show_waitlist: false,
        disable_styles: false,
        hide_bay_number: false,
        hide_level_selector_on_booking_list: false,
        hide_users: false,
        hide_vehicles: false,
        hide_users_and_vehicles: false,
        hide_availability_counter: false,
        hide_assign_space: false,
        allow_deleting: false,
        assign_space_on_approve: false,
        max_assigned_count: 0,
        custom_booking_columns: [],
    },
    events: {
        allow_setup_breakdown: false,
        use_building_timezone: false,
        day_timeline_view: 'inverted',
        block_start: 7,
        block_end: 19,
        block_height: 5,
        custom_actions: [
            {
                id: 'set_setup_breakdown',
                name: 'Set Setup/Breakdown',
                icon: 'manage_history',
            },
        ],
    },
    locales: [
        { id: 'en-AU', name: 'LANGUAGE.ENGLISH', local: 'English', flag: '🇦🇺' },
        {
            id: 'en-US',
            name: 'LANGUAGE.ENGLISH_US',
            local: 'English (US)',
            flag: '🇺🇸',
        },
        { id: 'fr', name: 'LANGUAGE.FRENCH', local: 'Français', flag: '🇫🇷' },
        {
            id: 'fr-CA',
            name: 'LANGUAGE.FRENCH_CA',
            local: 'Français (Canada)',
            flag: '🇨🇦',
        },
        { id: 'es', name: 'LANGUAGE.SPANISH', local: 'Español', flag: '🇪🇸' },
        {
            id: 'pt',
            name: 'LANGUAGE.PORTUGUESE',
            local: 'Português',
            flag: '🇵🇹',
        },
        { id: 'it', name: 'LANGUAGE.ITALIAN', local: 'Italiano', flag: '🇮🇹' },
        { id: 'zh', name: 'LANGUAGE.CHINESE', local: '中文', flag: '🇨🇳' },
        { id: 'ja-JP', name: 'LANGUAGE.JAPANESE', local: '日本語', flag: '🇯🇵' },
        { id: 'ar', name: 'LANGUAGE.ARABIC', local: 'عربية', flag: '' },
    ],
    catering: {
        use_bookings: true,
    },
};

/**
 * ROOT SETTIGNS
 */
export const DEFAULT_SETTINGS: any = {
    debug: true,
    composer: {
        domain: '',
        route: '/concierge',
        protocol: '',
        port: '',
        use_domain: false,
        local_login: false,
    },
    app,
};
