const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const {
    cpSync,
    mkdirSync,
    mkdtempSync,
    rmSync,
    symlinkSync,
} = require('node:fs');
const { tmpdir } = require('node:os');
const path = require('node:path');
const { test } = require('node:test');
const { cleanMessage } = require('./git-hooks');

const ATTRIBUTION = 'Co-Authored-By: Claude Sonnet <noreply@anthropic.com>';

function fixture(context, environment = {}) {
    const directory = mkdtempSync(path.join(tmpdir(), 'git-hooks-'));
    context.after(() => rmSync(directory, { recursive: true, force: true }));
    const repo = path.join(directory, 'repo');
    const remote = path.join(directory, 'remote.git');
    mkdirSync(repo);

    function run(...args) {
        return spawnSync('git', args, {
            cwd: repo,
            encoding: 'utf8',
            env: {
                ...process.env,
                GIT_CONFIG_GLOBAL: '/dev/null',
                GIT_CONFIG_NOSYSTEM: '1',
                GIT_TERMINAL_PROMPT: '0',
                ...environment,
            },
        });
    }

    function git(...args) {
        const result = run(...args);
        assert.equal(result.status, 0, result.stderr);
        return result.stdout.trim();
    }

    git('init', '--initial-branch=main');
    git('config', 'user.name', 'Hook Test');
    git('config', 'user.email', 'hook-test@example.com');
    git('config', 'commit.gpgSign', 'false');
    git('init', '--bare', remote);
    git('remote', 'add', 'origin', remote);
    cpSync(path.join(__dirname, '../.githooks'), path.join(repo, '.githooks'), {
        recursive: true,
    });
    mkdirSync(path.join(repo, 'tools'));
    cpSync(
        __filename.replace('.test.js', '.js'),
        path.join(repo, 'tools/git-hooks.js'),
    );
    cpSync(
        path.join(__dirname, 'run-git-hook.sh'),
        path.join(repo, 'tools/run-git-hook.sh'),
    );
    git('config', 'core.hooksPath', '.githooks');

    function commit(message, bypass = false) {
        git(
            'commit',
            '--allow-empty',
            ...(bypass ? ['--no-verify'] : []),
            '-m',
            message,
        );
        return git('rev-parse', 'HEAD');
    }

    return { run, git, commit, directory };
}

test('both hooks find Bun outside PATH in a GUI environment', (context) => {
    const environment = {};
    const { git, commit, directory } = fixture(context, environment);
    const bun_install = path.join(directory, 'Bun Install');
    mkdirSync(path.join(bun_install, 'bin'), { recursive: true });
    symlinkSync(process.execPath, path.join(bun_install, 'bin/bun'));
    environment.PATH = '/usr/bin:/bin';
    environment.BUN_INSTALL = bun_install;

    commit(`fix: GUI commit\n\n${ATTRIBUTION}`);
    assert.equal(git('log', '-1', '--format=%B'), 'fix: GUI commit');
    git('push', 'origin', 'main');
});

test('hooks use Node.js when Bun is unavailable', (context) => {
    const node = spawnSync('node', ['-p', 'process.execPath'], {
        encoding: 'utf8',
    });
    assert.equal(node.status, 0, node.stderr);
    const environment = {};
    const { git, commit, directory } = fixture(context, environment);
    const bin = path.join(directory, 'bin');
    mkdirSync(bin);
    symlinkSync(node.stdout.trim(), path.join(bin, 'node'));
    environment.PATH = `${bin}:/usr/bin:/bin`;
    environment.BUN_INSTALL = path.join(directory, 'missing-bun');

    commit(`fix: Node commit\n\n${ATTRIBUTION}`);
    assert.equal(git('log', '-1', '--format=%B'), 'fix: Node commit');
    git('push', 'origin', 'main');
});

test('a missing runtime stops the hook with setup instructions', (context) => {
    const environment = {};
    const { run, directory } = fixture(context, environment);
    environment.PATH = '/usr/bin:/bin';
    environment.BUN_INSTALL = path.join(directory, 'missing-bun');
    const result = run('commit', '--allow-empty', '-m', 'fix: missing runtime');
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /Git hooks need Bun or Node.js/);
});

test('removes attribution variants and preserves human co-authors and message text', () => {
    const message =
        'fix: repair the Claude integration\r\n\r\n' +
        'See https://claude.ai for the API.\r\n' +
        'Co-Authored-By: Claude Smith <claude@example.com>\r\n' +
        'Co-Authored-By: Alex <alex@example.com>\r\n';
    for (const footer of [
        ATTRIBUTION,
        'co-authored-by: Claude Opus 4.6 <claude@anthropic.com>',
        '🤖 Generated with [Claude Code](https://claude.ai/code)',
        'Generated by Claude',
    ]) {
        assert.equal(cleanMessage(message + footer + '\r\n'), message);
        assert.equal(cleanMessage(message + footer), message);
    }
    assert.equal(cleanMessage(message), message);
});

test('git commit runs the cleanup hook', (context) => {
    const { git, commit } = fixture(context);
    commit(
        `fix: example\n\n${ATTRIBUTION}\nCo-Authored-By: Alex <alex@example.com>`,
    );
    assert.equal(
        git('log', '-1', '--format=%B'),
        'fix: example\n\nCo-Authored-By: Alex <alex@example.com>',
    );
});

test('initial push is blocked without rewriting and succeeds after amendment', (context) => {
    const { run, git, commit } = fixture(context);
    const original = commit(`fix: example\n\n${ATTRIBUTION}`, true);
    const blocked = run('push', 'origin', 'main');
    assert.notEqual(blocked.status, 0);
    assert.match(blocked.stderr, /Claude attribution found/);
    assert.ok(blocked.stderr.includes(original.slice(0, 12)));
    assert.equal(git('rev-parse', 'HEAD'), original);
    assert.equal(git('ls-remote', 'origin'), '');

    git('commit', '--amend', '--no-edit', '--allow-empty');
    git('push', 'origin', 'main');
    assert.ok(
        git('ls-remote', 'origin', 'main').startsWith(git('rev-parse', 'HEAD')),
    );
});

test('new branches skip known remote history but check every new commit', (context) => {
    const { run, git, commit } = fixture(context);
    commit(`legacy commit\n\n${ATTRIBUTION}`, true);
    git('push', '--no-verify', 'origin', 'main');
    git('switch', '-c', 'feature');
    commit('feat: clean message');
    git('push', 'origin', 'feature');

    const bad = commit(`fix: intermediate commit\n\n${ATTRIBUTION}`, true);
    commit('fix: clean tip');
    const blocked = run('push', 'origin', 'feature');
    assert.notEqual(blocked.status, 0);
    assert.ok(blocked.stderr.includes(bad.slice(0, 12)));
});

test('push checks tags and all branches and permits ref deletion', (context) => {
    const { run, git, commit } = fixture(context);
    commit('initial commit');
    git('push', 'origin', 'main');
    git('switch', '-c', 'dirty');
    commit(`fix: example\n\n${ATTRIBUTION}`, true);
    git('tag', '-a', 'dirty-tag', '-m', 'tag message');
    git('switch', 'main');
    commit('clean branch update');
    assert.notEqual(run('push', 'origin', 'main', 'dirty').status, 0);
    assert.notEqual(run('push', 'origin', 'dirty-tag').status, 0);
    git('push', 'origin', 'main:refs/heads/temporary');
    git('push', 'origin', ':refs/heads/temporary');
});

test('force pushes check replacement history', (context) => {
    const { run, git, commit } = fixture(context);
    const base = commit('base');
    commit('old tip');
    git('push', 'origin', 'main');
    git('reset', '--hard', base);
    commit(`replacement\n\n${ATTRIBUTION}`, true);
    assert.notEqual(run('push', '--force', 'origin', 'main').status, 0);
});
