import { Injectable } from '@angular/core';
import { Observable, BehaviorSubject } from 'rxjs';
import { BaseClass } from '@placeos/common';

export enum QuestionType {
    text = 'text',
    checkbox = 'checkbox',
    dropdown = 'dropdown',
    rating = 'rating',
}
export interface Question {
    type: QuestionType;
    name: string;
    title: string;
    choices?: any[];
}

@Injectable({
    providedIn: 'root',
})
export class CreateSurveyService extends BaseClass {
    //Store of survey questions generated by user
    private _questions: BehaviorSubject<Question[]> = new BehaviorSubject<
        Question[]
    >([]);
    questions$: Observable<Question[]> = this._questions.asObservable();

    set questions(questions: Question[]) {
        this._questions.next(questions);
    }

    get questions() {
        return this._questions.getValue();
    }

    constructor() {
        super();
    }
}
